# Generated by Django 4.2.5 on 2023-09-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_childprofile_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('IC', 'Inappropriate Content'), ('OP', 'Obscenities and Profanity'), ('VC', 'Violent and Disturbing Content'), ('OL', 'Offensive Language')], default='IC', max_length=2)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile')),
            ],
            options={
                'verbose_name': 'Banned Word',
                'verbose_name_plural': 'Banned Words',
            },
        ),
        migrations.CreateModel(
            name='SearchPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=256)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('allowed', models.BooleanField(default=False)),
                ('searched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
            ],
            options={
                'verbose_name': 'Search Phrase',
                'verbose_name_plural': 'Search Phrases',
            },
        ),
        migrations.CreateModel(
            name='FlaggedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_on', models.DateTimeField(auto_now_add=True)),
                ('flagged_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safesearch.bannedword')),
                ('search_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safesearch.searchphrase')),
            ],
            options={
                'verbose_name': 'Flagged Word',
                'verbose_name_plural': 'Flagged Words',
            },
        ),
        migrations.CreateModel(
            name='FlaggedSearches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_on', models.DateTimeField(auto_now_add=True)),
                ('search_phrase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safesearch.searchphrase')),
            ],
            options={
                'verbose_name': 'Flagged Search',
                'verbose_name_plural': 'Flagged Searches ',
            },
        ),
    ]
