# Generated by Django 5.0a1 on 2023-11-04 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_title', models.CharField(max_length=250)),
                ('result_link', models.URLField(max_length=250)),
                ('result_snippet', models.TextField()),
                ('report_reason', models.TextField()),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(limit_choices_to={'user_type': 'CH'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_reported_results', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_reported_results', to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safesearch.searchphrase')),
            ],
            options={
                'verbose_name': 'Result Report',
                'verbose_name_plural': 'Result Reports',
                'ordering': ['-reported_on'],
            },
        ),
    ]
