# Generated by Django 4.2.5 on 2023-09-17 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlaggedSearches',
            new_name='FlaggedSearch',
        ),
    ]
