# Generated by Django 5.0a1 on 2023-11-04 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0002_resultreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultreport',
            name='parent',
        ),
        migrations.AlterField(
            model_name='resultreport',
            name='child',
            field=models.ForeignKey(limit_choices_to={'user_type': 'CH'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
