# Generated by Django 4.2.5 on 2023-09-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0004_searchphrase_no_of_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchphrase',
            name='searched_on',
            field=models.DateTimeField(null=True),
        ),
    ]
