# Generated by Django 5.0a1 on 2023-11-04 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0004_sitevisite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_link', models.URLField(max_length=250)),
                ('site_title', models.CharField(max_length=250)),
                ('site_snippet', models.TextField()),
                ('visited_on', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(limit_choices_to={'user_type': 'CH'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safesearch.searchphrase')),
            ],
            options={
                'verbose_name': 'Site Visite',
                'verbose_name_plural': 'Site Visites',
                'ordering': ['-visited_on'],
            },
        ),
        migrations.DeleteModel(
            name='SiteVisite',
        ),
    ]
