# Generated by Django 4.2.5 on 2023-09-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0005_searchphrase_searched_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchphrase',
            name='searched_on',
        ),
    ]
