# Generated by Django 5.0a1 on 2023-11-05 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0007_resultreport_parent_alter_resultreport_child'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultreport',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportedhildrenresults', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitevisit',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'user_type': 'PR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siteschildrenvisited', to=settings.AUTH_USER_MODEL),
        ),
    ]
