# Generated by Django 4.2.5 on 2023-09-20 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers_and_more'),
        ('safesearch', '0007_searchphrase_searched_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaggedword',
            name='search_phrase',
        ),
        migrations.AddField(
            model_name='flaggedword',
            name='flagged_search',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='safesearch.flaggedsearch'),
        ),
        migrations.AlterField(
            model_name='flaggedalert',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile'),
        ),
    ]
