# Generated by Django 5.0.4 on 2024-04-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0008_alter_resultreport_parent_alter_sitevisit_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitevisit',
            options={'ordering': ['-visited_on'], 'verbose_name': 'Site Visit', 'verbose_name_plural': 'Site Visits'},
        ),
    ]
