# Generated by Django 4.2.5 on 2023-09-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0008_remove_flaggedword_search_phrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flaggedalert',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='flaggedalert',
            name='flagged_search',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safesearch.flaggedsearch'),
        ),
    ]
