# Generated by Django 4.2.5 on 2023-09-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers_and_more'),
        ('safesearch', '0009_remove_flaggedalert_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedalert',
            name='reviewed_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile'),
        ),
    ]
