# Generated by Django 4.2.5 on 2023-09-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0013_bannedword_banned_defaults'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannedword',
            old_name='banned_defaults',
            new_name='banned_default',
        ),
    ]
