# Generated by Django 5.0a1 on 2023-10-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_confirmation'),
        ('safesearch', '0014_rename_banned_defaults_bannedword_banned_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_results', models.PositiveIntegerField(editable=False)),
                ('been_reviewed', models.BooleanField(default=False)),
                ('reviewed_on', models.DateTimeField(null=True)),
                ('seen_by_child', models.BooleanField(default=False)),
                ('seen_on', models.DateTimeField(null=True)),
                ('search_phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safesearch.searchphrase')),
            ],
            options={
                'verbose_name': 'Suspicious Search',
                'verbose_name_plural': 'Suspicious Searches',
            },
        ),
        migrations.CreateModel(
            name='UnbanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('been_reviewed', models.BooleanField(default=False)),
                ('reviewed_on', models.DateTimeField(null=True)),
                ('seen_by_child', models.BooleanField(default=False)),
                ('seen_on', models.DateTimeField(null=True)),
                ('banned_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safesearch.bannedword')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
            ],
            options={
                'verbose_name': 'Unban Request',
                'verbose_name_plural': 'Unban Requests',
            },
        ),
    ]
