# Generated by Django 4.2.5 on 2023-09-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0014_rename_banned_defaults_bannedword_banned_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannedword',
            old_name='banned_default',
            new_name='dafault_ban',
        ),
    ]
