# Generated by Django 5.0a1 on 2023-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0015_suspicioussearch_unbanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedalert',
            name='flagged_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
