# Generated by Django 4.2.5 on 2023-09-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0015_rename_banned_default_bannedword_dafault_ban'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannedword',
            old_name='dafault_ban',
            new_name='default_ban',
        ),
    ]
