# Generated by Django 5.0a1 on 2023-10-05 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0016_flaggedalert_flagged_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedalert',
            options={'ordering': ['-flagged_on'], 'verbose_name': 'Flagged Alert', 'verbose_name_plural': 'Flagged Alerts'},
        ),
    ]
