# Generated by Django 4.2.5 on 2023-09-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0016_rename_dafault_ban_bannedword_default_ban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannedword',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='bannedword',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='bannedword',
            name='default_ban',
        ),
        migrations.AddField(
            model_name='bannedword',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
