# Generated by Django 5.0a1 on 2023-10-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_parentprofile_photo'),
        ('safesearch', '0017_alter_flaggedalert_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedalert',
            name='searched_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile'),
        ),
    ]
