# Generated by Django 4.2.5 on 2023-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0017_remove_bannedword_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedword',
            name='default_ban',
            field=models.BooleanField(default=False),
        ),
    ]
