# Generated by Django 5.0a1 on 2023-10-05 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0018_flaggedalert_searched_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flaggedalert',
            options={'ordering': ['been_reviewed', '-flagged_on'], 'verbose_name': 'Flagged Alert', 'verbose_name_plural': 'Flagged Alerts'},
        ),
    ]
