# Generated by Django 5.0a1 on 2023-10-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0019_alter_flaggedalert_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannedword',
            options={'ordering': ['word'], 'verbose_name': 'Banned Word', 'verbose_name_plural': 'Banned Words'},
        ),
        migrations.RemoveField(
            model_name='bannedword',
            name='banned_default',
        ),
        migrations.AddField(
            model_name='bannedword',
            name='is_banned',
            field=models.BooleanField(default=True),
        ),
    ]
