# Generated by Django 4.2.5 on 2023-09-24 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safesearch', '0019_unbanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedword',
            name='been_unbanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unbanrequest',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unbanrequest',
            name='review_response',
            field=models.CharField(choices=[('AP', 'Approved'), ('DE', 'Denied')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='unbanrequest',
            name='requested_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'CH'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
