# Generated by Django 5.0a1 on 2023-10-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0021_alter_searchphrase_options_unbanrequest_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unbanrequest',
            old_name='request_timestamp',
            new_name='requested_on',
        ),
        migrations.AddField(
            model_name='unbanrequest',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
