# Generated by Django 5.0a1 on 2023-10-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_childprofile_account_status'),
        ('safesearch', '0024_alter_unbanrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedsearch',
            name='searched_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile'),
        ),
    ]
