# Generated by Django 5.0a1 on 2023-10-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0025_flaggedsearch_searched_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchphrase',
            name='allowed',
        ),
        migrations.AddField(
            model_name='searchphrase',
            name='search_status',
            field=models.CharField(choices=[('SF', 'Safe'), ('SP', 'Suspicious'), ('FL', 'Flagged')], default='SF', max_length=2),
        ),
    ]
