# Generated by Django 5.0a1 on 2023-10-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0028_delete_suspicioussearch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchphrase',
            options={'ordering': ['-searched_on'], 'verbose_name': 'Search Phrase', 'verbose_name_plural': 'Search Phrases'},
        ),
    ]
