# Generated by Django 5.0a1 on 2023-10-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_childprofile_last_seen_alter_parentprofile_gender'),
        ('safesearch', '0029_alter_searchphrase_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlaggedAlert',
            new_name='SearchAlert',
        ),
    ]
