# Generated by Django 5.0a1 on 2023-10-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_childsettings'),
        ('safesearch', '0030_rename_flaggedalert_searchalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedword',
            name='banned_for',
            field=models.ManyToManyField(to='accounts.childprofile'),
        ),
        migrations.AddField(
            model_name='bannedword',
            name='banned_type',
            field=models.CharField(choices=[('P', 'Phrase'), ('W', 'Word')], default='W', max_length=2),
        ),
    ]
