# Generated by Django 5.0a1 on 2023-10-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0031_bannedword_banned_for_bannedword_banned_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('SH', 'Shopping'), ('DR', 'Drugs'), ('GB', 'Gambling'), ('DT', 'Dating'), ('SM', 'Social Media'), ('AC', 'Adult Content'), ('GM', 'Games'), ('VS', 'Video Sites'), ('CB', 'Cyberbullying'), ('HS', 'Hate Speech'), ('VL', 'Violence'), ('PF', 'Profanity'), ('IC', 'Inappropriate Content')], default='IC', max_length=2)),
                ('banned_type', models.CharField(choices=[('P', 'Phrase'), ('W', 'Word')], default='W', max_length=2)),
            ],
            options={
                'verbose_name': 'BannedDefault',
                'verbose_name_plural': 'BannedDefaults',
            },
        ),
    ]
