# Generated by Django 5.0a1 on 2023-10-31 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0032_banneddefault'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banneddefault',
            old_name='reason',
            new_name='category',
        ),
    ]
