# Generated by Django 5.0a1 on 2023-10-31 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0033_rename_reason_banneddefault_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='banneddefault',
            unique_together={('word', 'category')},
        ),
    ]
