# Generated by Django 5.0a1 on 2023-11-01 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_childprofile_search_frequency_limit_and_more'),
        ('safesearch', '0036_alter_bannedword_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banneddefault',
            options={'verbose_name': 'Banned Default', 'verbose_name_plural': 'Banned Defaults'},
        ),
        migrations.AddField(
            model_name='bannedword',
            name='from_default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DefaultByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=250, null=True)),
                ('shopping', models.BooleanField(default=False)),
                ('drugs', models.BooleanField(default=False)),
                ('gambling', models.BooleanField(default=False)),
                ('dating', models.BooleanField(default=False)),
                ('social_media', models.BooleanField(default=False)),
                ('adult_content', models.BooleanField(default=False)),
                ('games', models.BooleanField(default=False)),
                ('video_sites', models.BooleanField(default=False)),
                ('cyberbullying', models.BooleanField(default=False)),
                ('violence', models.BooleanField(default=False)),
                ('profanity', models.BooleanField(default=False)),
                ('inappropriate_content', models.BooleanField(default=False)),
                ('child_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
            ],
            options={
                'verbose_name': 'Default Banned Category',
                'verbose_name_plural': 'Default Banned Categories',
                'ordering': ['child_profile'],
            },
        ),
    ]
