# Generated by Django 5.0a1 on 2023-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0038_alter_banneddefault_category_alter_bannedword_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneddefault',
            name='category',
            field=models.CharField(choices=[('IC', 'Inappropriate Content'), ('OP', 'Obscenities and Profanity'), ('VC', 'Violent and Disturbing Content'), ('OL', 'Offensive Language'), ('DR', 'Drugs'), ('GB', 'Gambling'), ('DT', 'Dating'), ('SM', 'Social Media'), ('GM', 'Games'), ('VS', 'Video Sites'), ('SH', 'Shopping')], default='IC', max_length=2),
        ),
        migrations.AlterField(
            model_name='bannedword',
            name='reason',
            field=models.CharField(choices=[('IC', 'Inappropriate Content'), ('OP', 'Obscenities and Profanity'), ('VC', 'Violent and Disturbing Content'), ('OL', 'Offensive Language'), ('DR', 'Drugs'), ('GB', 'Gambling'), ('DT', 'Dating'), ('SM', 'Social Media'), ('GM', 'Games'), ('VS', 'Video Sites'), ('SH', 'Shopping')], default='IC', max_length=2),
        ),
    ]
