# Generated by Django 5.0a1 on 2023-11-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0039_alter_banneddefault_category_alter_bannedword_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannedword',
            name='word',
            field=models.CharField(max_length=250),
        ),
    ]
