# Generated by Django 5.0a1 on 2023-11-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0040_alter_bannedword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneddefault',
            name='word',
            field=models.CharField(max_length=250),
        ),
    ]
