# Generated by Django 5.0a1 on 2023-11-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safesearch', '0041_alter_banneddefault_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneddefault',
            name='category',
            field=models.CharField(choices=[('VC', 'Violent and Disturbing Content'), ('OL', 'Offensive Language'), ('DR', 'Drugs'), ('AC', 'Adult Content')], default='OL', max_length=2),
        ),
        migrations.AlterField(
            model_name='bannedword',
            name='reason',
            field=models.CharField(choices=[('VC', 'Violent and Disturbing Content'), ('OL', 'Offensive Language'), ('DR', 'Drugs'), ('AC', 'Adult Content')], default='OL', max_length=2),
        ),
    ]
