# Generated by Django 5.0a1 on 2023-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type_of_comment',
            field=models.CharField(choices=[('R', 'Reply'), ('O', 'Original')], default='R', max_length=1),
        ),
    ]
