# Generated by Django 5.0a1 on 2023-10-31 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_childprofile_search_frequency_limit_and_more'),
        ('forum', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile'),
        ),
    ]
