# Generated by Django 5.0a1 on 2023-11-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_comment_reply_by_post_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-contact_on'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactresponse',
            options={'ordering': ['-responded_on'], 'verbose_name': 'Contact Response', 'verbose_name_plural': 'Contact Responses'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_on'], 'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
