# Generated by Django 5.0a1 on 2023-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_comment_comment_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
