# Generated by Django 5.0a1 on 2023-11-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_comment_comment_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
