# Generated by Django 5.0a1 on 2023-11-03 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_post_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply_by',
            new_name='comment_by',
        ),
    ]
