# Generated by Django 5.0a1 on 2023-11-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_rename_reply_by_comment_comment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
