# Generated by Django 4.2.5 on 2023-09-17 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_childprofile_gender_parentprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile'),
        ),
    ]
