# Generated by Django 4.2.5 on 2023-09-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_childprofile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PR', 'Parent'), ('CH', 'Child')], editable=False, max_length=2),
        ),
    ]
