# Generated by Django 4.2.5 on 2023-09-18 08:28

import accounts.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('parents', accounts.models.ParentManager()),
                ('children', accounts.models.ChildManager()),
            ],
        ),
        migrations.RenameField(
            model_name='childprofile',
            old_name='parent',
            new_name='parent_profile',
        ),
    ]
