# Generated by Django 5.0a1 on 2023-10-05 20:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.parent_profile_photo_path),
        ),
    ]
