# Generated by Django 4.2.5 on 2023-09-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('expires_on', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='account_status',
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('AC', 'Active'), ('BN', 'Banned')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
        migrations.AddField(
            model_name='accountconfirmation',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
