# Generated by Django 4.2.5 on 2023-09-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountconfirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfirmation',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'PR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='child',
            field=models.OneToOneField(limit_choices_to={'user_type': 'CH'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='parent',
            field=models.OneToOneField(limit_choices_to={'user_type': 'PR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
