# Generated by Django 4.2.5 on 2023-09-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accountconfirmation_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('AC', 'Actived'), ('NA', 'Not Activated')], default='NA', max_length=2, null=True),
        ),
    ]
