# Generated by Django 5.0a1 on 2023-10-05 20:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_childprofile_photo_parentprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, default='static/img/user.png', upload_to=accounts.models.parent_profile_photo_path),
        ),
    ]
