# Generated by Django 4.2.5 on 2023-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('AC', 'Actived'), ('NA', 'Not Activated')], default='NA', max_length=2),
        ),
    ]
