# Generated by Django 4.2.5 on 2023-09-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_account_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountConfirmation',
            new_name='Confirmation',
        ),
    ]
