# Generated by Django 5.0a1 on 2023-10-16 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_parentprofile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmation',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='confirmation',
            name='expires_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'PR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
