# Generated by Django 5.0a1 on 2023-10-17 18:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_confirmation_options_confirmation_expires_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.parent_profile_photo_path),
        ),
    ]
