# Generated by Django 5.0a1 on 2023-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_childprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='account_status',
            field=models.CharField(choices=[('AC', 'Active'), ('BN', 'Banned')], default='AC', max_length=2),
        ),
    ]
