# Generated by Django 5.0a1 on 2023-10-22 07:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_childprofile_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.child_profile_photo_path),
        ),
    ]
