# Generated by Django 5.0a1 on 2023-10-22 08:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_childprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/avatars/child.png', null=True, upload_to=accounts.models.child_profile_photo_path),
        ),
    ]
