# Generated by Django 5.0a1 on 2023-10-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_childprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='avatar',
        ),
    ]
