# Generated by Django 5.0a1 on 2023-10-22 08:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_childprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/priest/Code/childprotect/staticfiles/avatars/child.png', null=True, upload_to=accounts.models.child_profile_photo_path),
        ),
    ]
