# Generated by Django 5.0a1 on 2023-10-22 08:29

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_childprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.child_profile_photo_path),
        ),
    ]
