# Generated by Django 5.0a1 on 2023-10-30 04:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_childprofile_last_seen_alter_parentprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('S', 'Strict'), ('M', 'Moderate'), ('L', 'Low')], default='M', max_length=10)),
                ('search_time_start', models.TimeField(blank=True, default=datetime.datetime(1, 1, 1, 5, 32, 44, tzinfo=datetime.timezone.utc), null=True)),
                ('search_time_end', models.TimeField(blank=True, default=datetime.datetime(1, 1, 1, 15, 32, 44, tzinfo=datetime.timezone.utc), null=True)),
                ('search_frequency_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of searches allowed within the time period', null=True)),
                ('child', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parentprofile')),
            ],
        ),
    ]
