# Generated by Django 5.0a1 on 2023-10-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_childprofile_alert_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='search_frequency_limit',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='search_time_end',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='search_time_start',
        ),
    ]
