# Generated by Django 5.0a1 on 2023-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_childprofile_search_frequency_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='banned_default_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
